version: '3'
services:
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - benchmark

  benchmark:
    build: .
    expose:
      - "80"
